#!/bin/bash

BIN=./bin/basename
TESTS=0
SUCCESS=0

eq(){
	TESTS=$((${TESTS} + 1))
	if test $1 = $2; then
	       	SUCCESS=$((${SUCCESS} + 1))
	else 
		echo "!!!: $1 != $2"
	fi
}

eq $(${BIN} "//test") "test"
eq $(${BIN} "////") "/"
eq $(${BIN} "") ""
eq $(${BIN} "//test/kekw") "kekw"
eq $(${BIN} "//test/kekw//") "kekw"
eq $(${BIN} "//test/kekw.mp3//" ".mp3") "kekw"

echo $(basename $0)":" ${SUCCESS} "/" ${TESTS}

