#!/bin/bash

BIN=./bin/dirname
TESTS=0
SUCCESS=0

eq(){
	TESTS=$((${TESTS} + 1))
	if test $1 = $2; then
	       	SUCCESS=$((${SUCCESS} + 1))
	else 
		echo "!!!: $1 != $2"
	fi
}

eq $(${BIN} "//test") "/"
eq $(${BIN} "////") "/"
eq $(${BIN} "") "/"
eq $(${BIN} "//test/kekw") "//test"
eq $(${BIN} "//test/kekw//") "//test"
eq $(${BIN} "test/") "."

echo $(basename $0)":" ${SUCCESS} "/" ${TESTS}

