#!/bin/bash

BIN=./bin/echo
TESTS=0
SUCCESS=0

eq(){
	TESTS=$((${TESTS} + 1))
	if test "$1" = "$2"; then
	       	SUCCESS=$((${SUCCESS} + 1))
	else 
		echo "!!!: $1 != $2"
	fi
}

eq "$(${BIN} lmao)" "lmao"
eq "$(${BIN} lmao kekw)" "lmao kekw"

echo $(basename $0)":" ${SUCCESS} "/" ${TESTS}
